default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV.fetch("DATABASE") { "sharetribe_#{Rails.env}" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "127.0.0.1" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 3306 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "root" } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
